dashboards:
  default:
    bitovi-expanded-dashboard-github:
      url: https://raw.githubusercontent.com/bitovi/Temporal-Self-Hosting-Workshop-Exercises/main/grafana/bitovi_expanded_dashboard.json
      datasource: TemporalMetrics
    benchmark-workshop-dashboard-github:
      url: https://raw.githubusercontent.com/bitovi/Temporal-Self-Hosting-Workshop-Exercises/main/grafana/benchmark_workshop_dashboard.json
      datasource: TemporalMetrics
    replication-dashboard-github:
      url: https://raw.githubusercontent.com/bitovi/Temporal-Self-Hosting-Workshop-Exercises/main/grafana/replication_dashboard.json
      datasource: TemporalMetrics
    server-general-github:
      url: https://raw.githubusercontent.com/temporalio/dashboards/helm/server/server-general.json
      datasource: TemporalMetrics
    sdk-general-github:
      url: https://raw.githubusercontent.com/temporalio/dashboards/helm/sdk/sdk-general.json
      datasource: TemporalMetrics
    misc-advanced-visibility-specific-github:
      url: https://raw.githubusercontent.com/temporalio/dashboards/helm/misc/advanced-visibility-specific.json
      datasource: TemporalMetrics
    misc-clustermonitoring-kubernetes-github:
      url: https://raw.githubusercontent.com/temporalio/dashboards/helm/misc/clustermonitoring-kubernetes.json
      datasource: TemporalMetrics
    misc-frontend-service-specific-github:
      url: https://raw.githubusercontent.com/temporalio/dashboards/helm/misc/frontend-service-specific.json
      datasource: TemporalMetrics
    misc-history-service-specific-github:
      url: https://raw.githubusercontent.com/temporalio/dashboards/helm/misc/history-service-specific.json
      datasource: TemporalMetrics
    misc-matching-service-specific-github:
      url: https://raw.githubusercontent.com/temporalio/dashboards/helm/misc/matching-service-specific.json
      datasource: TemporalMetrics
    misc-worker-service-specific-github:
      url: https://raw.githubusercontent.com/temporalio/dashboards/helm/misc/worker-service-specific.json
      datasource: TemporalMetrics
