server:
  replicaCount: 1
  additionalEnv:
    - name: AWS_ACCESS_KEY_ID
      value: admin
    - name: AWS_SECRET_ACCESS_KEY
      value: temporal
  archival:
    history:
      state: "enabled"
      enableRead: true
      provider:
        s3store:
          region: us-east-1
          endpoint: "http://minio:9000"
          accessKey: admin
          secretKey: temporal
          insecure: true
          s3ForcePathStyle: true
    visibility:
      state: "enabled"
      enableRead: true
      provider:
        s3store:
          region: us-east-1
          endpoint: "http://minio:9000"
          accessKey: admin
          secretKey: temporal
          insecure: true
          s3ForcePathStyle: true

  config:
    numHistoryShards: 256
    persistence:
      default:
        driver: "sql"
        sql:
          driver: "postgres12"
          host: postgresql.default.svc.cluster.local
          port: 5432
          database: temporal_persistence
          user: temporal
          password: temporal
          maxConns: 20
          maxIdleConns: 20
          maxConnLifetime: "1h"
      visibility:
        driver: "sql"
        sql:
          driver: "postgres12"
          host: postgresql.default.svc.cluster.local
          port: 5432
          database: temporal_visibility
          user: temporal
          password: temporal
          maxConns: 20
          maxIdleConns: 20
          maxConnLifetime: "1h"
    clusterMetadata:
      enableGlobalNamespace: true
      failoverVersionIncrement: 10
      masterClusterName: "cluster-1"
      currentClusterName: "cluster-1"
      clusterInformation:
        cluster-1:
          enabled: true
          initialFailoverVersion: 1
          rpcAddress: "cluster-1-temporal-frontend:7233"
        cluster-2:
          enabled: true
          initialFailoverVersion: 2
          rpcAddress: "cluster-2-temporal-frontend:7233"  

  namespaceDefaults:
    archival:
      history:
        state: 'enabled'
        URI: 's3://temporal-archival/history'
      visibility:
        state: 'enabled'
        URI: 's3://temporal-visibility/visibility'

  frontend:
    service:
      type: NodePort
      port: 7233
      targetPort: 7233
      nodePort: 30233

  history:
    service:
      type: ClusterIP
      port: 7234
      targetPort: 7234

  matching:
    service:
      type: ClusterIP
      port: 7235
      targetPort: 7235

  worker:
    service:
      type: ClusterIP
      port: 7239
      targetPort: 7239

web:
  service:
    type: NodePort
    port: 8080
    targetPort: 8080
    nodePort: 30080
  
