server:
  replicaCount: 1
  image:
    tag: 1.28.0
  archival:
    history:
      state: "enabled"
      enableRead: true
      provider:
        s3store:
          region: us-east-1
          endpoint: "http://minio:9000"
          accessKey: admin
          secretKey: temporal
          insecure: true
          s3ForcePathStyle: true
    visibility:
      state: "enabled"
      enableRead: true
      provider:
        s3store:
          region: us-east-1
          endpoint: "http://minio:9000"
          accessKey: admin
          secretKey: temporal
          insecure: true
          s3ForcePathStyle: true

  config:
    persistence:
      defaultStore: default
      visibilityStore: visibility
      # Important: numHistoryShards cannot be changed after the initial deployment.
      numHistoryShards: 256
      datastores:
        default:
          sql:
            pluginName: postgres12
            driverName: postgres12
            connectAddr: postgresql.default.svc.cluster.local:5432
            connectProtocol: tcp
            databaseName: temporal_persistence_2
            user: temporal
            password: temporal
            maxConns: 20
            maxIdleConns: 20
            maxConnLifetime: "1h"
        visibility:
          sql:
            pluginName: postgres12
            driverName: postgres12
            connectAddr: postgresql.default.svc.cluster.local:5432
            connectProtocol: tcp
            databaseName: temporal_visibility_2
            user: temporal
            password: temporal
            maxConns: 20
            maxIdleConns: 20
            maxConnLifetime: "1h"    
    clusterMetadata:
      enableGlobalNamespace: true
      failoverVersionIncrement: 10
      masterClusterName: "cluster-1"
      currentClusterName: "cluster-2"
      clusterInformation:
        cluster-1:
          enabled: true
          initialFailoverVersion: 1
          rpcAddress: "cluster-1-temporal-frontend:7233"
        cluster-2:
          enabled: true
          initialFailoverVersion: 2
          rpcAddress: "cluster-2-temporal-frontend:8233"
  namespaceDefaults:
    archival:
      history:
        state: 'enabled'
        URI: 's3://temporal-archival/history'
      visibility:
        state: 'enabled'
        URI: 's3://temporal-visibility/visibility'

  frontend:
    service:
      type: NodePort
      port: 8233
      httpPort: 7243
      targetPort: 7233
      nodePort: 31233

admintools:
  additionalEnv:
    - name: SQL_USER
      value: postgres

web:
  service:
    type: NodePort
    port: 8080
    targetPort: 8080
    nodePort: 31080

